using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DelegateBy.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class DelegateByGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "DelegateBy.DelegateByAttribute";

    private const string AttributeSource = """
// <auto-generated/>
#nullable enable
namespace DelegateBy
{
    [global::System.Diagnostics.Conditional("DELEGATEBY_ATTRIBUTES")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class DelegateByAttribute : global::System.Attribute
    {
        public DelegateByAttribute(global::System.Type interfaceType, string memberName)
        {
            InterfaceType = interfaceType;
            MemberName = memberName;
        }

        public global::System.Type InterfaceType { get; }
        public string MemberName { get; }
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("DelegateByAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
            static (attributeContext, _) => new Candidate(
                (INamedTypeSymbol)attributeContext.TargetSymbol,
                attributeContext.Attributes));

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(candidates.Collect()),
            static (output, pair) => Execute(pair.Left, pair.Right, output));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<Candidate> candidates,
        SourceProductionContext context)
    {
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var candidate in candidates)
        {
            if (!seen.Add(candidate.Type))
            {
                continue;
            }

            ProcessType(compilation, candidate, context);
        }
    }

    private static void ProcessType(
        Compilation compilation,
        Candidate candidate,
        SourceProductionContext context)
    {
        var type = candidate.Type;
        var hasError = false;

        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (!IsPartial(current))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PartialRequired,
                    current.Locations.FirstOrDefault(),
                    current.ToDisplayString()));
                hasError = true;
            }
        }

        var mappings = new List<DelegationMapping>();
        var mappedInterfaces = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var attribute in candidate.Attributes)
        {
            var location = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation()
                ?? type.Locations.FirstOrDefault();

            var interfaceType = attribute.ConstructorArguments.Length > 0
                ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
                : null;
            var memberName = attribute.ConstructorArguments.Length > 1
                ? attribute.ConstructorArguments[1].Value as string
                : null;

            if (interfaceType is null ||
                interfaceType.TypeKind != TypeKind.Interface ||
                interfaceType.IsUnboundGenericType ||
                ContainsTypeParameter(interfaceType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InterfaceRequired,
                    location,
                    interfaceType?.ToDisplayString() ?? "<unknown>"));
                hasError = true;
                continue;
            }

            if (!mappedInterfaces.Add(interfaceType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateInterface,
                    location,
                    interfaceType.ToDisplayString()));
                hasError = true;
                continue;
            }

            if (string.IsNullOrWhiteSpace(memberName))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DelegateNotFound,
                    location,
                    type.ToDisplayString(),
                    memberName ?? string.Empty));
                hasError = true;
                continue;
            }

            // The whitespace/null cases returned above, so subsequent symbol lookup is safe.
            var validMemberName = memberName!;

            var namedMembers = type.GetMembers(validMemberName);
            var usableMembers = namedMembers.Where(IsUsableDelegateMember).ToArray();
            if (usableMembers.Length == 0)
            {
                var descriptor = namedMembers.Length == 0
                    ? Diagnostics.DelegateNotFound
                    : Diagnostics.InvalidDelegate;
                var arguments = namedMembers.Length == 0
                    ? new object[] { type.ToDisplayString(), validMemberName }
                    : new object[] { validMemberName };
                context.ReportDiagnostic(Diagnostic.Create(descriptor, location, arguments));
                hasError = true;
                continue;
            }

            if (usableMembers.Length != 1)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InvalidDelegate, location, validMemberName));
                hasError = true;
                continue;
            }

            var delegateMember = usableMembers[0];
            var delegateType = GetDelegateType(delegateMember)!;
            var conversion = compilation.ClassifyConversion(delegateType, interfaceType);
            if (!conversion.IsImplicit)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.IncompatibleDelegate,
                    location,
                    validMemberName,
                    delegateType.ToDisplayString(),
                    interfaceType.ToDisplayString()));
                hasError = true;
                continue;
            }

            mappings.Add(new DelegationMapping(interfaceType, delegateMember, location));
        }

        var planned = new Dictionary<string, PlannedMember>(StringComparer.Ordinal);

        foreach (var mapping in mappings)
        {
            foreach (var member in GetInterfaceMembers(mapping.InterfaceType))
            {
                if (!RequiresImplementation(member))
                {
                    continue;
                }

                var existing = FindExisting(type, member);
                if (existing.Kind == ExistingKind.Compatible)
                {
                    continue;
                }

                if (existing.Kind == ExistingKind.Conflicting)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ExistingMemberMismatch,
                        existing.Symbol?.Locations.FirstOrDefault() ?? mapping.Location,
                        existing.Symbol?.Name ?? member.Name,
                        member.ToDisplayString()));
                    hasError = true;
                    continue;
                }

                if (IsUnsupported(member))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.UnsupportedMember,
                        mapping.Location,
                        member.ToDisplayString(),
                        type.ToDisplayString()));
                    hasError = true;
                    continue;
                }

                var key = GetCallableKey(member);
                if (planned.TryGetValue(key, out var prior))
                {
                    if (!SymbolEqualityComparer.Default.Equals(prior.Mapping.DelegateMember, mapping.DelegateMember) ||
                        !ContractsCanShareImplementation(prior.Primary, member))
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            Diagnostics.AmbiguousDelegation,
                            mapping.Location,
                            member.ToDisplayString(),
                            type.ToDisplayString()));
                        hasError = true;
                        continue;
                    }

                    prior.Contracts.Add(member);
                    continue;
                }

                planned.Add(key, new PlannedMember(member, mapping));
            }
        }

        if (hasError || mappings.Count == 0)
        {
            return;
        }

        var source = SourceEmitter.Emit(type, mappings, planned.Values);
        context.AddSource(GetHintName(type), SourceText.From(source, Encoding.UTF8));
    }

    private static bool IsPartial(INamedTypeSymbol type) =>
        type.DeclaringSyntaxReferences.Length > 0 &&
        type.DeclaringSyntaxReferences.All(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax declaration &&
            declaration.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static bool IsUsableDelegateMember(ISymbol member) => member switch
    {
        IFieldSymbol field => !field.IsStatic,
        IPropertySymbol property => !property.IsStatic && property.GetMethod is not null && !property.IsIndexer,
        _ => false,
    };

    private static ITypeSymbol? GetDelegateType(ISymbol member) => member switch
    {
        IFieldSymbol field => field.Type,
        IPropertySymbol property => property.Type,
        _ => null,
    };

    private static IEnumerable<ISymbol> GetInterfaceMembers(INamedTypeSymbol interfaceType)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var current in interfaceType.AllInterfaces.Reverse().Concat(new[] { interfaceType }))
        {
            foreach (var member in current.GetMembers())
            {
                var key = GetContractKey(member);
                if (seen.Add(key))
                {
                    yield return member;
                }
            }
        }
    }

    private static bool RequiresImplementation(ISymbol member) => member switch
    {
        IMethodSymbol method => method.MethodKind is MethodKind.Ordinary or
            MethodKind.UserDefinedOperator or MethodKind.Conversion,
        IPropertySymbol => true,
        IEventSymbol => true,
        _ => false,
    };

    private static bool IsUnsupported(ISymbol member) => member switch
    {
        IMethodSymbol method => method.IsStatic || method.MethodKind != MethodKind.Ordinary,
        IPropertySymbol property => property.IsStatic || property.SetMethod?.IsInitOnly == true,
        IEventSymbol @event => @event.IsStatic,
        _ => true,
    };

    private static ExistingResult FindExisting(INamedTypeSymbol type, ISymbol contract)
    {
        ISymbol? conflicting = null;

        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
        {
            foreach (var candidate in current.GetMembers(contract.Name))
            {
                if (!HasSameCallableShape(candidate, contract))
                {
                    continue;
                }

                if (IsCompatibleImplementation(candidate, contract))
                {
                    return new ExistingResult(ExistingKind.Compatible, candidate);
                }

                conflicting ??= candidate;
            }

            if (contract is IPropertySymbol { IsIndexer: true })
            {
                foreach (var candidate in current.GetMembers().OfType<IPropertySymbol>().Where(p => p.IsIndexer))
                {
                    if (!HasSameCallableShape(candidate, contract))
                    {
                        continue;
                    }

                    if (IsCompatibleImplementation(candidate, contract))
                    {
                        return new ExistingResult(ExistingKind.Compatible, candidate);
                    }

                    conflicting ??= candidate;
                }
            }
        }

        return conflicting is null
            ? new ExistingResult(ExistingKind.None, null)
            : new ExistingResult(ExistingKind.Conflicting, conflicting);
    }

    private static bool HasSameCallableShape(ISymbol candidate, ISymbol contract)
    {
        if (candidate.Kind != contract.Kind)
        {
            return false;
        }

        return (candidate, contract) switch
        {
            (IMethodSymbol left, IMethodSymbol right) =>
                left.Name == right.Name &&
                left.Arity == right.Arity &&
                ParametersEqual(left.Parameters, right.Parameters, includeTypes: true),
            (IPropertySymbol left, IPropertySymbol right) =>
                left.IsIndexer == right.IsIndexer &&
                (left.IsIndexer || left.Name == right.Name) &&
                ParametersEqual(left.Parameters, right.Parameters, includeTypes: true),
            (IEventSymbol left, IEventSymbol right) => left.Name == right.Name,
            _ => false,
        };
    }

    private static bool IsCompatibleImplementation(ISymbol candidate, ISymbol contract)
    {
        if (candidate.DeclaredAccessibility != Accessibility.Public || candidate.IsStatic != contract.IsStatic)
        {
            return false;
        }

        return (candidate, contract) switch
        {
            (IMethodSymbol left, IMethodSymbol right) =>
                TypeEquals(left.ReturnType, right.ReturnType) &&
                left.RefKind == right.RefKind &&
                ConstraintsEqual(left, right),
            (IPropertySymbol left, IPropertySymbol right) =>
                TypeEquals(left.Type, right.Type) &&
                left.RefKind == right.RefKind &&
                (right.GetMethod is null || left.GetMethod is { DeclaredAccessibility: Accessibility.Public }) &&
                (right.SetMethod is null || left.SetMethod is { DeclaredAccessibility: Accessibility.Public }),
            (IEventSymbol left, IEventSymbol right) => TypeEquals(left.Type, right.Type),
            _ => false,
        };
    }

    private static bool ParametersEqual(
        ImmutableArray<IParameterSymbol> left,
        ImmutableArray<IParameterSymbol> right,
        bool includeTypes)
    {
        if (left.Length != right.Length)
        {
            return false;
        }

        for (var index = 0; index < left.Length; index++)
        {
            if (left[index].RefKind != right[index].RefKind ||
                (includeTypes && !TypeEquals(left[index].Type, right[index].Type)))
            {
                return false;
            }
        }

        return true;
    }

    private static bool ConstraintsEqual(IMethodSymbol left, IMethodSymbol right)
    {
        if (left.TypeParameters.Length != right.TypeParameters.Length)
        {
            return false;
        }

        for (var index = 0; index < left.TypeParameters.Length; index++)
        {
            var l = left.TypeParameters[index];
            var r = right.TypeParameters[index];
            if (l.HasConstructorConstraint != r.HasConstructorConstraint ||
                l.HasReferenceTypeConstraint != r.HasReferenceTypeConstraint ||
                l.HasValueTypeConstraint != r.HasValueTypeConstraint ||
                l.HasUnmanagedTypeConstraint != r.HasUnmanagedTypeConstraint ||
                l.HasNotNullConstraint != r.HasNotNullConstraint ||
                l.ConstraintTypes.Length != r.ConstraintTypes.Length)
            {
                return false;
            }

            for (var constraintIndex = 0; constraintIndex < l.ConstraintTypes.Length; constraintIndex++)
            {
                if (!TypeEquals(l.ConstraintTypes[constraintIndex], r.ConstraintTypes[constraintIndex]))
                {
                    return false;
                }
            }
        }

        return true;
    }

    private static bool TypeEquals(ITypeSymbol left, ITypeSymbol right)
    {
        if (left is ITypeParameterSymbol ltp && right is ITypeParameterSymbol rtp &&
            ltp.TypeParameterKind == TypeParameterKind.Method &&
            rtp.TypeParameterKind == TypeParameterKind.Method)
        {
            return ltp.Ordinal == rtp.Ordinal;
        }

        if (left is IArrayTypeSymbol la && right is IArrayTypeSymbol ra)
        {
            return la.Rank == ra.Rank && TypeEquals(la.ElementType, ra.ElementType);
        }

        if (left is IPointerTypeSymbol lp && right is IPointerTypeSymbol rp)
        {
            return TypeEquals(lp.PointedAtType, rp.PointedAtType);
        }

        if (left is INamedTypeSymbol ln && right is INamedTypeSymbol rn)
        {
            if (!SymbolEqualityComparer.Default.Equals(ln.OriginalDefinition, rn.OriginalDefinition) ||
                ln.TypeArguments.Length != rn.TypeArguments.Length)
            {
                return false;
            }

            for (var i = 0; i < ln.TypeArguments.Length; i++)
            {
                if (!TypeEquals(ln.TypeArguments[i], rn.TypeArguments[i]))
                {
                    return false;
                }
            }

            return true;
        }

        return SymbolEqualityComparer.Default.Equals(left, right);
    }

    private static bool ContainsTypeParameter(ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => true,
        IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType),
        IPointerTypeSymbol pointer => ContainsTypeParameter(pointer.PointedAtType),
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsTypeParameter),
        _ => false,
    };

    private static bool ContractsCanShareImplementation(ISymbol left, ISymbol right) =>
        (left, right) switch
        {
            (IMethodSymbol lm, IMethodSymbol rm) =>
                TypeEquals(lm.ReturnType, rm.ReturnType) && lm.RefKind == rm.RefKind,
            (IPropertySymbol lp, IPropertySymbol rp) =>
                TypeEquals(lp.Type, rp.Type) && lp.RefKind == rp.RefKind,
            (IEventSymbol le, IEventSymbol re) => TypeEquals(le.Type, re.Type),
            _ => false,
        };

    private static string GetCallableKey(ISymbol symbol) => symbol switch
    {
        IMethodSymbol method => "M:" + method.Name + "`" + method.Arity + "(" +
            string.Join(",", method.Parameters.Select(ParameterKey)) + ")",
        IPropertySymbol property => "P:" + (property.IsIndexer ? "this" : property.Name) + "(" +
            string.Join(",", property.Parameters.Select(ParameterKey)) + ")",
        IEventSymbol @event => "E:" + @event.Name,
        _ => symbol.Kind + ":" + symbol.Name,
    };

    private static string GetContractKey(ISymbol symbol) =>
        GetCallableKey(symbol) + symbol switch
        {
            IMethodSymbol method => ":" + TypeKey(method.ReturnType) + ":" + method.RefKind,
            IPropertySymbol property => ":" + TypeKey(property.Type) + ":" + property.RefKind +
                ":" + (property.GetMethod is not null) + ":" + (property.SetMethod is not null),
            IEventSymbol @event => ":" + TypeKey(@event.Type),
            _ => string.Empty,
        };

    private static string ParameterKey(IParameterSymbol parameter) =>
        parameter.RefKind + ":" + TypeKey(parameter.Type);

    private static string TypeKey(ITypeSymbol type)
    {
        if (type is ITypeParameterSymbol { TypeParameterKind: TypeParameterKind.Method } methodParameter)
        {
            return "!!" + methodParameter.Ordinal;
        }

        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GetHintName(INamedTypeSymbol type)
    {
        var identity = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sanitized = new string(identity.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray());
        var hash = 2166136261u;
        foreach (var ch in identity)
        {
            hash = (hash ^ ch) * 16777619u;
        }

        return sanitized + "_" + hash.ToString("x8") + ".DelegateBy.g.cs";
    }

    private sealed class Candidate
    {
        internal Candidate(INamedTypeSymbol type, ImmutableArray<AttributeData> attributes)
        {
            Type = type;
            Attributes = attributes;
        }

        internal INamedTypeSymbol Type { get; }
        internal ImmutableArray<AttributeData> Attributes { get; }
    }

    internal sealed class DelegationMapping
    {
        internal DelegationMapping(INamedTypeSymbol interfaceType, ISymbol delegateMember, Location? location)
        {
            InterfaceType = interfaceType;
            DelegateMember = delegateMember;
            Location = location;
        }

        internal INamedTypeSymbol InterfaceType { get; }
        internal ISymbol DelegateMember { get; }
        internal Location? Location { get; }
    }

    internal sealed class PlannedMember
    {
        internal PlannedMember(ISymbol primary, DelegationMapping mapping)
        {
            Primary = primary;
            Mapping = mapping;
            Contracts = new List<ISymbol> { primary };
        }

        internal ISymbol Primary { get; }
        internal DelegationMapping Mapping { get; }
        internal List<ISymbol> Contracts { get; }
    }

    private enum ExistingKind
    {
        None,
        Compatible,
        Conflicting,
    }

    private readonly struct ExistingResult
    {
        internal ExistingResult(ExistingKind kind, ISymbol? symbol)
        {
            Kind = kind;
            Symbol = symbol;
        }

        internal ExistingKind Kind { get; }
        internal ISymbol? Symbol { get; }
    }
}
