using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DelegateBy.Generator;

internal static class SourceEmitter
{
    private static readonly SymbolDisplayFormat TypeDisplayFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions:
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    internal static string Emit(
        INamedTypeSymbol type,
        IReadOnlyCollection<DelegateByGenerator.DelegationMapping> mappings,
        IEnumerable<DelegateByGenerator.PlannedMember> members)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS0612, CS0618");

        var indent = 0;
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ")
                .Append(type.ContainingNamespace.ToDisplayString())
                .AppendLine();
            builder.AppendLine("{");
            indent++;
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var containing = type.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            containingTypes.Push(containing);
        }

        foreach (var containing in containingTypes)
        {
            AppendIndent(builder, indent);
            builder.Append("partial ")
                .Append(GetTypeKeyword(containing))
                .Append(' ')
                .Append(Escape(containing.Name))
                .Append(TypeParameters(containing.TypeParameters))
                .AppendLine();
            AppendTypeConstraints(builder, containing.TypeParameters, indent);
            AppendIndent(builder, indent);
            builder.AppendLine("{");
            indent++;
        }

        AppendIndent(builder, indent);
        builder.Append("partial ")
            .Append(GetTypeKeyword(type))
            .Append(' ')
            .Append(Escape(type.Name))
            .Append(TypeParameters(type.TypeParameters));

        var newInterfaces = mappings
            .Select(mapping => mapping.InterfaceType)
            .Where(@interface => !type.Interfaces.Any(existing =>
                SymbolEqualityComparer.Default.Equals(existing, @interface)))
            .ToArray();

        if (newInterfaces.Length > 0)
        {
            builder.Append(" : ")
                .Append(string.Join(", ", newInterfaces.Select(item => TypeName(item))));
        }

        builder.AppendLine();
        AppendTypeConstraints(builder, type.TypeParameters, indent);
        AppendIndent(builder, indent);
        builder.AppendLine("{");
        indent++;

        var first = true;
        foreach (var member in members.OrderBy(item => item.Primary.Name, StringComparer.Ordinal))
        {
            if (!first)
            {
                builder.AppendLine();
            }

            first = false;
            EmitMember(builder, member, indent);
        }

        indent--;
        AppendIndent(builder, indent);
        builder.AppendLine("}");

        while (containingTypes.Count > 0)
        {
            containingTypes.Pop();
            indent--;
            AppendIndent(builder, indent);
            builder.AppendLine("}");
        }

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitMember(
        StringBuilder builder,
        DelegateByGenerator.PlannedMember planned,
        int indent)
    {
        AppendGeneratedAttributes(builder, indent);

        switch (planned.Primary)
        {
            case IMethodSymbol method:
                EmitMethod(builder, method, planned.Mapping, indent);
                break;
            case IPropertySymbol property:
                EmitProperty(builder, property, planned, indent);
                break;
            case IEventSymbol @event:
                EmitEvent(builder, @event, planned.Mapping, indent);
                break;
        }
    }

    private static void EmitMethod(
        StringBuilder builder,
        IMethodSymbol method,
        DelegateByGenerator.DelegationMapping mapping,
        int indent)
    {
        AppendIndent(builder, indent);
        builder.Append("public ");
        if (ContainsPointer(method.ReturnType) || method.Parameters.Any(parameter => ContainsPointer(parameter.Type)))
        {
            builder.Append("unsafe ");
        }

        builder.Append(RefReturn(method.RefKind))
            .Append(TypeName(method.ReturnType))
            .Append(' ')
            .Append(Escape(method.Name))
            .Append(TypeParameters(method.TypeParameters))
            .Append('(')
            .Append(string.Join(", ", method.Parameters.Select(FormatParameter)))
            .AppendLine(")");

        AppendTypeConstraints(builder, method.TypeParameters, indent);
        AppendIndent(builder, indent + 1);
        builder.Append("=> ");
        if (method.RefKind is RefKind.Ref or RefKind.RefReadOnly)
        {
            builder.Append("ref ");
        }

        builder.Append(DelegateExpression(mapping))
            .Append('.')
            .Append(Escape(method.Name))
            .Append(TypeArguments(method.TypeParameters))
            .Append('(')
            .Append(string.Join(", ", method.Parameters.Select(FormatArgument)))
            .AppendLine(");");
    }

    private static void EmitProperty(
        StringBuilder builder,
        IPropertySymbol property,
        DelegateByGenerator.PlannedMember planned,
        int indent)
    {
        var needsGetter = planned.Contracts.OfType<IPropertySymbol>().Any(item => item.GetMethod is not null);
        var needsSetter = planned.Contracts.OfType<IPropertySymbol>().Any(item => item.SetMethod is not null);

        AppendIndent(builder, indent);
        builder.Append("public ");
        if (ContainsPointer(property.Type) || property.Parameters.Any(parameter => ContainsPointer(parameter.Type)))
        {
            builder.Append("unsafe ");
        }

        builder.Append(RefReturn(property.RefKind))
            .Append(TypeName(property.Type))
            .Append(' ');

        if (property.IsIndexer)
        {
            builder.Append("this[")
                .Append(string.Join(", ", property.Parameters.Select(FormatParameter)))
                .Append(']');
        }
        else
        {
            builder.Append(Escape(property.Name));
        }

        builder.AppendLine();
        AppendIndent(builder, indent);
        builder.AppendLine("{");

        var access = property.IsIndexer
            ? "[" + string.Join(", ", property.Parameters.Select(FormatArgument)) + "]"
            : "." + Escape(property.Name);
        var expression = DelegateExpression(planned.Mapping) + access;

        if (needsGetter)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("get => ");
            if (property.RefKind is RefKind.Ref or RefKind.RefReadOnly)
            {
                builder.Append("ref ");
            }

            builder.Append(expression).AppendLine(";");
        }

        if (needsSetter)
        {
            AppendIndent(builder, indent + 1);
            builder.Append("set => ").Append(expression).AppendLine(" = value;");
        }

        AppendIndent(builder, indent);
        builder.AppendLine("}");
    }

    private static void EmitEvent(
        StringBuilder builder,
        IEventSymbol @event,
        DelegateByGenerator.DelegationMapping mapping,
        int indent)
    {
        AppendIndent(builder, indent);
        builder.Append("public event ")
            .Append(TypeName(@event.Type))
            .Append(' ')
            .Append(Escape(@event.Name))
            .AppendLine();
        AppendIndent(builder, indent);
        builder.AppendLine("{");
        AppendIndent(builder, indent + 1);
        builder.Append("add => ").Append(DelegateExpression(mapping)).Append('.')
            .Append(Escape(@event.Name)).AppendLine(" += value;");
        AppendIndent(builder, indent + 1);
        builder.Append("remove => ").Append(DelegateExpression(mapping)).Append('.')
            .Append(Escape(@event.Name)).AppendLine(" -= value;");
        AppendIndent(builder, indent);
        builder.AppendLine("}");
    }

    private static void AppendGeneratedAttributes(StringBuilder builder, int indent)
    {
        AppendIndent(builder, indent);
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"DelegateBy\", \"0.1.0\")]");
        AppendIndent(builder, indent);
        builder.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        AppendIndent(builder, indent);
        builder.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]");
    }

    private static string DelegateExpression(DelegateByGenerator.DelegationMapping mapping) =>
        "((" + TypeName(mapping.InterfaceType) + ")this." + Escape(mapping.DelegateMember.Name) + ")";

    private static string FormatParameter(IParameterSymbol parameter)
    {
        var builder = new StringBuilder();
        if (parameter.ScopedKind != ScopedKind.None)
        {
            builder.Append("scoped ");
        }

        if (parameter.IsParams)
        {
            builder.Append("params ");
        }

        builder.Append(RefParameter(parameter.RefKind))
            .Append(TypeName(parameter.Type))
            .Append(' ')
            .Append(Escape(parameter.Name));

        if (parameter.HasExplicitDefaultValue && parameter.RefKind == RefKind.None)
        {
            builder.Append(" = ").Append(FormatDefaultValue(parameter));
        }

        return builder.ToString();
    }

    private static string FormatArgument(IParameterSymbol parameter) =>
        RefArgument(parameter.RefKind) + Escape(parameter.Name);

    private static string FormatDefaultValue(IParameterSymbol parameter)
    {
        var value = parameter.ExplicitDefaultValue;
        if (value is null)
        {
            return "default";
        }

        if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            return "(" + TypeName(parameter.Type) + ")" + Convert.ToString(value, CultureInfo.InvariantCulture);
        }

        return value switch
        {
            string text => SymbolDisplay.FormatLiteral(text, quote: true),
            char character => SymbolDisplay.FormatLiteral(character, quote: true),
            bool boolean => boolean ? "true" : "false",
            float single when float.IsNaN(single) => "global::System.Single.NaN",
            float single when float.IsPositiveInfinity(single) => "global::System.Single.PositiveInfinity",
            float single when float.IsNegativeInfinity(single) => "global::System.Single.NegativeInfinity",
            float single => single.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number when double.IsNaN(number) => "global::System.Double.NaN",
            double number when double.IsPositiveInfinity(number) => "global::System.Double.PositiveInfinity",
            double number when double.IsNegativeInfinity(number) => "global::System.Double.NegativeInfinity",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "default",
        };
    }

    private static void AppendTypeConstraints(
        StringBuilder builder,
        ImmutableArray<ITypeParameterSymbol> parameters,
        int indent)
    {
        foreach (var parameter in parameters)
        {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (parameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }
            else if (parameter.HasReferenceTypeConstraint)
            {
                constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                    ? "class?"
                    : "class");
            }
            else if (parameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            constraints.AddRange(parameter.ConstraintTypes.Select(TypeName));
            if (parameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count == 0)
            {
                continue;
            }

            AppendIndent(builder, indent + 1);
            builder.Append("where ")
                .Append(Escape(parameter.Name))
                .Append(" : ")
                .Append(string.Join(", ", constraints))
                .AppendLine();
        }
    }

    private static string TypeParameters(ImmutableArray<ITypeParameterSymbol> parameters) =>
        parameters.IsDefaultOrEmpty
            ? string.Empty
            : "<" + string.Join(", ", parameters.Select(parameter => Escape(parameter.Name))) + ">";

    private static string TypeArguments(ImmutableArray<ITypeParameterSymbol> parameters) =>
        TypeParameters(parameters);

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(TypeDisplayFormat);

    private static string GetTypeKeyword(INamedTypeSymbol type)
    {
        if (type.IsRecord)
        {
            return type.TypeKind == TypeKind.Struct ? "record struct" : "record class";
        }

        return type.TypeKind switch
        {
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class",
        };
    }

    private static bool ContainsPointer(ITypeSymbol type) => type switch
    {
        IPointerTypeSymbol => true,
        IArrayTypeSymbol array => ContainsPointer(array.ElementType),
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsPointer),
        _ => false,
    };

    private static string RefReturn(RefKind refKind) => refKind switch
    {
        RefKind.Ref => "ref ",
        RefKind.RefReadOnly => "ref readonly ",
        _ => string.Empty,
    };

    private static string RefParameter(RefKind refKind) => refKind switch
    {
        RefKind.Ref => "ref ",
        RefKind.Out => "out ",
        RefKind.In => "in ",
        RefKind.RefReadOnlyParameter => "ref readonly ",
        _ => string.Empty,
    };

    private static string RefArgument(RefKind refKind) => refKind switch
    {
        RefKind.Ref => "ref ",
        RefKind.Out => "out ",
        RefKind.In => "in ",
        RefKind.RefReadOnlyParameter => "in ",
        _ => string.Empty,
    };

    private static string Escape(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
        SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;

    private static void AppendIndent(StringBuilder builder, int indent) =>
        builder.Append(' ', indent * 4);
}
